spaceone-dev/console-api

config/default.json
src/add-ons/autocomplete/config.json
src/add-ons/autocomplete/controller.js
src/add-ons/autocomplete/routes/index.js

Add autocomplete feature

---

src/controllers/statistics/topic/cloud-service-by-region.js
src/controllers/statistics/topic/cloud-service-count.js
src/controllers/statistics/topic/cloud-service-type-page.js
src/controllers/statistics/topic/daily-cloud-service-count.js
src/controllers/statistics/topic/daily-job-summary.js
src/controllers/statistics/topic/daily-project-count.js
src/controllers/statistics/topic/daily-server-count.js
src/controllers/statistics/topic/daily-update-cloud-service.js
src/controllers/statistics/topic/daily-update-server.js
src/controllers/statistics/topic/project-count.js
src/controllers/statistics/topic/server-by-region.js
src/controllers/statistics/topic/server-count.js
src/controllers/statistics/topic/service-account-by-provider.js
src/controllers/statistics/topic/service-account-summary.js
src/controllers/statistics/topic/top-project.js
src/routes/statistics/topic.js

Add stat APIs for console

---

src/add-ons/autocomplete/config.json

Change autocomplete user format

---

src/controllers/statistics/topic/daily-update-cloud-service.js
src/lib/authentication.js

Change daily update period

---

src/lib/grpc-client/index.js

Add debug code

---

config/default.json

Remove health check log

---

src/lib/authentication.js
src/lib/logger.js

Exclude CORS log

---

src/lib/grpc-client/index.js

Remove debug code

---

src/add-ons/page-discovery/controller.js

add search_key option to page-discovery api

---

src/add-ons/autocomplete/controller.js
src/lib/grpc-client/index.js

add distinct query to autocomplete add-on

---

src/controllers/repository/policy/index.js
src/routes/repository/index.js
src/routes/repository/policy.js

Add repository policy APIs

---

config/default.json

Change logger and authentication settings

---

package-lock.json
package.json
src/app.js
src/lib/api.js

Add a reflection api

---

src/controllers/statistics/topic/cloud-service-type-page.js

Change a cloud-service-type-page topic parameter

---

src/controllers/statistics/topic/cloud-service-type-page.js

BugFix: parameter type checking issue

---

config/default.json

Reflection api except authentication

---

src/controllers/inventory/job-task/index.js
src/routes/inventory/index.js
src/routes/inventory/job-task.js

Add job and job-task api

---

src/controllers/statistics/topic/cloud-service-type-page.js
src/controllers/statistics/topic/daily-job-summary.js

Add start and end parameter to daily job summary

---

src/controllers/statistics/topic/cloud-service-type-page.js

Add query.keyword parameter to cloud service type page

---

config/default.json
src/controllers/report/domain/index.js
src/controllers/report/report/index.js
src/controllers/report/schedule/index.js
src/controllers/report/template/index.js
src/routes/index.js
src/routes/report/domain.js
src/routes/report/index.js
src/routes/report/report.js
src/routes/report/schedule.js
src/routes/report/template.js

Add report service apis

---

src/add-ons/autocomplete/controllers/resource.js

Change error format

---

src/add-ons/autocomplete/config.json
src/add-ons/page-discovery/config.json
src/add-ons/page-schema/controllers/identityServiceAccount/default-schema/details.json.tmpl
src/add-ons/page-schema/controllers/identityServiceAccount/default-schema/search.json.tmpl
src/add-ons/page-schema/controllers/identityServiceAccount/default-schema/table.json.tmpl

Change ejs template format

---

src/controllers/inventory/cloud-service/get-data.js
src/controllers/inventory/server/get-data.js

If get-data is empty, return empty array

---

src/controllers/statistics/topic/daily-update-cloud-service.js

Bug fix: add icon to daily update service

---

src/add-ons/page-schema/controllers/inventoryCloudService/default-schema/table.json.tmpl
src/add-ons/page-schema/controllers/inventoryServer/default-schema/table.json

Change page schema

---

src/add-ons/page-schema/controllers/identityServiceAccount/default-schema/table.json.tmpl

Bug fix: Change service account's page schema

---

src/add-ons/page-schema/controllers/inventoryServer/default-schema/table.json
src/controllers/statistics/topic/server-by-region.js

Bug fix: server's region key path

---

src/add-ons/page-schema/controllers/inventoryCloudService/default-schema/search.json.tmpl
src/add-ons/page-schema/controllers/inventoryServer/default-schema/search.json

Change server and cloud service search schema

---

package-lock.json
package.json
src/controllers/statistics/topic/daily-update-cloud-service.js
src/controllers/statistics/topic/daily-update-server.js

Add timezone parameter in daily update stat

---

package.json

Bugfix: package.json syntax

---

src/controllers/statistics/topic/secret-count.js

Bug fix: query filter

---

src/add-ons/page-schema/controllers/inventoryCloudService/index.js
src/add-ons/page-schema/controllers/inventoryServer/index.js

Change metadata schema format

---

src/controllers/statistics/topic/cloud-service-by-region.js
src/controllers/statistics/topic/server-by-region.js

Change aggregate region key at stat query

---

src/controllers/power-scheduler/schedule-rule/index.js
src/factories/statistics/topic/power-scheduler-resource-groups.js

Change power scheduler mock data

---

src/factories/power-scheduler/schedule.js

Change mock data

---

src/add-ons/aws-health/controllers/index.js

Apply api cache for 6 hours

---

src/add-ons/page-schema/controllers/inventoryCloudService/index.js
src/add-ons/page-schema/controllers/inventoryServer/index.js

Bug fix: failed to load deleted resource

---

src/add-ons/excel/lib/excel.js

Bug fix: excel default options issue

---

src/add-ons/page-schema/controllers/inventoryCloudService/default-schema/search.json.tmpl
src/add-ons/page-schema/controllers/inventoryServer/default-schema/search.json

Add search region filter

---

src/add-ons/autocomplete/config.json

Change a autocomplete region spec

---

src/lib/grpc-client/index.js

Add a debug code

---

package-lock.json
package.json
src/controllers/power-scheduler/schedule/schedule-resource-groups.js
src/factories/inventory/resource-group.js

Add power scheduler's resource group api

---

src/controllers/power-scheduler/schedule/schedule-resource-groups.js
src/routes/power-scheduler/schedule.js

Add power scheduler setting feature

---

src/controllers/power-scheduler/schedule/schedule-resource-groups.js
src/routes/power-scheduler/schedule.js

Add function to load default resource group when creating schedule

---

src/controllers/power-scheduler/schedule/schedule-resource-groups.js

Remove resource groups with the number of 0 when create a schedule

---

src/controllers/power-scheduler/schedule/schedule-resource-groups.js

Bug fix: fix response format

---

src/controllers/statistics/topic/power-schedule-schedules.js

Add a stat api (power scheduler schedules)

---

src/controllers/statistics/topic/power-schedule-schedules.js

Fill the default rule of the power scheduler stat api

---

src/add-ons/page-schema/controllers/inventoryServer/index.js
src/controllers/statistics/topic/power-schedule-resources.js

Bug fix: server search schema format

---

src/controllers/statistics/topic/power-schedule-resources.js
src/controllers/statistics/topic/power-schedule-schedules.js

Add a stat api (power scheduler resources)

---

src/controllers/statistics/topic/power-schedule-schedules.js

Bug fix: add default project data to power scheduler schedules

---

src/controllers/statistics/topic/cloud-service-by-region.js
src/controllers/statistics/topic/cloud-service-count.js

Include is_major filter when querying statistics

---

src/controllers/power-scheduler/schedule/index.js

Delete related resource group when deleting schedule

---

src/add-ons/page-schema/controllers/inventoryCloudService/index.js
src/add-ons/page-schema/controllers/inventoryServer/index.js
src/controllers/power-scheduler/schedule/schedule-resource-groups.js

Add include_id option to page schema addon

---

src/controllers/power-scheduler/schedule/schedule-resource-groups.js

Add a recommended field to get-create-schedule-resource-groups api

---

src/controllers/power-scheduler/schedule/schedule-resource-groups.js

bug fix: reverse recommended option

---

src/controllers/statistics/topic/power-schedule-schedules.js

add expected state to power-scheduler-schedules api

---

src/add-ons/page-schema/controllers/inventoryServer/index.js

bug fix: fix imported json data change issue

---

src/controllers/power-scheduler/schedule/schedule-resource-groups.js

bug fix: resource group null tags issue

---

src/controllers/power-scheduler/schedule/index.js

Refactor: change parameter

---

src/controllers/power-scheduler/schedule/index.js

Bug fix: power scheduler state issue

---

src/controllers/power-scheduler/schedule/index.js
src/controllers/statistics/topic/power-schedule-schedules.js

Bug fix: power scheduler's desire state issue

---

src/controllers/statistics/topic/cloud-service-type-page.js
src/controllers/statistics/topic/service-account-by-provider.js
src/controllers/statistics/topic/service-account-summary.js

Bug fix: statistics query bugs

---

src/add-ons/page-schema/controllers/identityServiceAccount/default-schema/details.json.tmpl
src/add-ons/page-schema/controllers/inventoryCloudService/default-schema/details.json
src/add-ons/page-schema/controllers/inventoryServer/default-schema/details.json
src/add-ons/page-schema/controllers/inventoryServer/default-schema/table.json

Add translation code to page schema api

---

Dockerfile
package-lock.json
package.json

Bug fix: grpc build issue

---

src/add-ons/page-schema/controllers/identityServiceAccount/default-schema/details.json.tmpl
src/add-ons/page-schema/controllers/inventoryCloudService/default-schema/details.json
src/add-ons/page-schema/controllers/inventoryCloudService/index.js
src/add-ons/page-schema/controllers/inventoryServer/default-schema/details.json
src/add-ons/page-schema/controllers/inventoryServer/index.js

Change page schema translation code

---

src/add-ons/page-schema/controllers/identityServiceAccount/default-schema/details.json.tmpl
src/add-ons/page-schema/controllers/inventoryCloudService/default-schema/details.json

Bug fix: json format issue

---

src/controllers/statistics/topic/cloud-service-type-page.js

Bug fix: cloud service filter issue

---

src/controllers/statistics/topic/daily-update-cloud-service.js
src/controllers/statistics/topic/daily-update-server.js

Add create and delete warning flag to daily update stat topic

---

src/controllers/statistics/topic/cloud-service-count.js
src/controllers/statistics/topic/cloud-service-type-page.js
src/controllers/statistics/topic/daily-database-count.js
src/controllers/statistics/topic/daily-storage-count.js
src/controllers/statistics/topic/daily-update-cloud-service.js
src/controllers/statistics/topic/daily-update-server.js
src/controllers/statistics/topic/server-by-provider.js
src/controllers/statistics/topic/server-count.js
src/routes/statistics/topic.js

Add server and cloud service statistics topic

---

src/controllers/statistics/topic/cloud-service-type-page.js

Add cloud_service_type_id field to cloud service type page stat api

---

src/controllers/statistics/topic/cloud-service-type-page.js

Bug fix: cloud_service_type_id reference issue

---

src/controllers/statistics/topic/cloud-service-resources.js
src/lib/grpc-client/proto/query.proto
src/routes/statistics/topic.js

Add a cloud service resources stat topic

---

src/controllers/statistics/topic/cloud-service-resources.js

Add fields option to cloud service resources stat api

---

src/controllers/statistics/topic/daily-update-cloud-service.js
src/controllers/statistics/topic/daily-update-server.js

Bug fix: daily update query

---

src/add-ons/page-schema/controllers/inventoryServer/default-schema/details.json
src/add-ons/page-schema/controllers/inventoryServer/default-schema/search.json

Add cloud service group and type to server's page schema

---

src/controllers/statistics/topic/cloud-service-by-region.js
src/controllers/statistics/topic/server-by-region.js

Change resource by region stat apis

---

src/add-ons/page-discovery/config.json
src/add-ons/page-discovery/controller.js

Add cloud service type to page discovery resource

---

src/controllers/power-scheduler/domain/index.js
src/routes/power-scheduler/domain.js
src/routes/power-scheduler/index.js

Add power scheduler's domain apis

---

src/controllers/statistics/topic/cloud-service-resources.js

Change cloud service resources topic query

---

src/controllers/statistics/topic/daily-update-cloud-service.js
src/controllers/statistics/topic/daily-update-server.js

Change daily updates warning level

---

src/controllers/statistics/topic/service-account-summary.js

Add major and primary filter to service account summary topic

---

src/add-ons/aws-health/controllers/index.js

Change a PHD eventType (accountNotification -> notification)

---

src/lib/grpc-client/index.js
src/lib/grpc-client/proto/tag.proto

Add a tag.proto for tag api

---

src/controllers/statistics/topic/cloud-service-resources.js
src/controllers/statistics/topic/daily-update-cloud-service.js
src/controllers/statistics/topic/daily-update-server.js

Change stat query

---

src/controllers/statistics/topic/cloud-service-resources.js
src/controllers/statistics/topic/daily-update-cloud-service.js
src/controllers/statistics/topic/daily-update-server.js
src/lib/utils.js

Bug fix: change tags format issue

---

src/controllers/statistics/topic/trusted-advisor-by-project.js
src/controllers/statistics/topic/trusted-advisor-summary.js
src/routes/statistics/topic.js

Add trusted advisor stat api

---

src/controllers/statistics/topic/trusted-advisor-by-project.js

Change stat api's response format

---

src/controllers/power-scheduler/schedule/schedule-resource-groups.js
src/factories/config/user-config.js
src/factories/inventory/resource-group.js
src/factories/power-scheduler/schedule-rule.js
src/factories/power-scheduler/schedule.js

Bug fix: fix a tags type issue

---

src/add-ons/page-schema/controllers/inventoryCloudService/default-schema/details.json
src/add-ons/page-schema/controllers/inventoryCloudService/default-schema/search.json.tmpl
src/add-ons/page-schema/controllers/inventoryCloudService/default-schema/table.json.tmpl
src/add-ons/page-schema/controllers/inventoryServer/default-schema/details.json
src/add-ons/page-schema/controllers/inventoryServer/default-schema/search.json
src/add-ons/page-schema/controllers/inventoryServer/default-schema/table.json

Change cloud service and server schema

---

src/add-ons/page-schema/controllers/inventoryCloudService/default-schema/details.json
src/add-ons/page-schema/controllers/inventoryCloudService/default-schema/search.json.tmpl
src/add-ons/page-schema/controllers/inventoryServer/default-schema/details.json
src/add-ons/page-schema/controllers/inventoryServer/default-schema/search.json
src/add-ons/page-schema/controllers/inventoryServer/default-schema/table.json

Change server and cloud service schema

---

src/add-ons/page-schema/controllers/inventoryServer/default-schema/details.json

Change server schema

---

src/controllers/statistics/topic/phd-events.js

Add sort option to phd events stat api

---

src/add-ons/autocomplete/config.json

Add a autocomplete resource (identity.Provider)

---

src/controllers/statistics/topic/phd-count-by-type.js
src/controllers/statistics/topic/phd-events.js

add period option to phd stat apis

---

src/controllers/statistics/topic/phd-summary.js

Add period option to phd summary stat api.

---

src/controllers/identity/project-group/index.js
src/controllers/identity/project/index.js

Refactor: modify project member process

---

src/controllers/identity/service-account/list-service-account-members.js
src/controllers/inventory/cloud-service/list-cloud-service-members.js
src/controllers/inventory/server/list-server-members.js

Bug fix: list resource's project member api

---

src/controllers/identity/project/index.js

Add a automatic role binding when add project member

---

src/add-ons/page-schema/controllers/inventoryServer/default-schema/search.json

Fix a search bug

---

src/add-ons/page-schema/controllers/index.js
src/controllers/power-scheduler/schedule/index.js
src/controllers/power-scheduler/schedule/schedule-resource-groups.js
src/routes/power-scheduler/schedule.js

Add resource type api for power scheduler

---

src/controllers/statistics/topic/phd-count-by-type.js
src/controllers/statistics/topic/phd-events.js
src/controllers/statistics/topic/phd-summary.js

Remove phd status_code filter for debugging

---

src/controllers/statistics/topic/cloud-service-summary.js

Add region filter to cloud service summary api

---

src/controllers/statistics/topic/cloud-service-summary.js
src/controllers/statistics/topic/daily-cloud-service-summary.js

Change supported labels in daily cloud service summary api

---

src/controllers/statistics/topic/daily-cloud-service-summary.js

Change required parameter when request daily cloud service summary api

---

src/controllers/statistics/topic/service-account-summary.js

Change service account summary api's response data

---

src/controllers/identity/project/index.js

Remove temporary core

---

src/controllers/statistics/topic/phd-summary.js

Change a phd filter conditions

---

src/controllers/statistics/topic/project-page.js
src/controllers/statistics/topic/top-project.js

Change project stat apis

---

src/controllers/statistics/topic/service-account-summary.js

Change a service account summary api's response data

---

src/controllers/identity/user/index.js

fix a user response

---

src/add-ons/page-schema/controllers/inventoryCloudService/default-schema/details.json
src/add-ons/page-schema/controllers/inventoryCloudService/default-schema/table.json.tmpl
src/add-ons/page-schema/controllers/inventoryServer/default-schema/details.json
src/add-ons/page-schema/controllers/inventoryServer/default-schema/table.json

Add a deleted state to collection states

---

src/controllers/identity/project/tree-project.js

Fix permissions error when loading project tree

---

src/controllers/identity/project/index.js

Change project delete process

---

src/controllers/power-scheduler/schedule/index.js

Fix supported power scheduler resource types

---

src/controllers/power-scheduler/schedule/index.js

Change power scheduler job status result

---

src/controllers/power-scheduler/schedule/index.js
src/controllers/statistics/topic/cloud-service-by-region.js
src/controllers/statistics/topic/cloud-service-resources.js
src/controllers/statistics/topic/cloud-service-summary.js
src/controllers/statistics/topic/daily-cloud-service-summary.js
src/controllers/statistics/topic/daily-job-summary.js
src/controllers/statistics/topic/daily-update-cloud-service.js
src/controllers/statistics/topic/daily-update-server.js
src/controllers/statistics/topic/phd-count-by-type.js
src/controllers/statistics/topic/phd-events.js
src/controllers/statistics/topic/phd-summary.js
src/controllers/statistics/topic/power-schedule-resources.js
src/controllers/statistics/topic/power-schedule-schedules.js
src/controllers/statistics/topic/project-page.js
src/controllers/statistics/topic/secret-count.js
src/controllers/statistics/topic/server-by-region.js
src/controllers/statistics/topic/service-account-by-provider.js
src/controllers/statistics/topic/service-account-summary.js
src/controllers/statistics/topic/top-project.js
src/controllers/statistics/topic/trusted-advisor-by-project.js
src/controllers/statistics/topic/trusted-advisor-summary.js
src/lib/grpc-client/index.js
src/lib/grpc-client/proto/query.proto

Change stat query spec

---

src/lib/grpc-client/index.js

Fix a grpc client bug

---

src/controllers/statistics/topic/daily-update-cloud-service.js

Fix a daily update cloud service bug

---

src/controllers/identity/project/tree-project.js

project group tree api 의 child check 최적화

Update project group tree child checking way

---

config/default.json
src/controllers/identity/domain-owner/index.js
src/controllers/identity/project-group/index.js
src/controllers/monitoring/log/index.js
src/controllers/spot-automation/controller/index.js
src/controllers/spot-automation/domain/index.js
src/controllers/spot-automation/job/index.js
src/controllers/spot-automation/spot-group/index.js
src/controllers/statistics/topic/power-schedule-schedules.js
src/lib/error.js
src/lib/grpc-client/index.js
src/routes/index.js
src/routes/spot-automation/controller.js
src/routes/spot-automation/domain.js
src/routes/spot-automation/index.js
src/routes/spot-automation/job.js
src/routes/spot-automation/spot-group.js

Spot automation API 추가
1. default.json에 spot-automation 관련 명세 추가 
2. spot automation controller 추가
3. spot automation routes 추가
1. stat api 적용 방법

Add spot automation api

---

src/controllers/identity/project/tree-project.js

프로젝트 그룹 트리 api 에 권한 체크 추가
1. 파라미터에 ```check_child```, ```include_permission``` 추가
2. 결과값에 ```has_permission``` 추가 (default: null)   
3. 로직 분리

Update project group tree api spec

---

src/controllers/power-scheduler/schedule/index.js

Change power scheduler's supported resource types

---

src/controllers/power-scheduler/schedule/index.js

Fix a stat query bug

---

src/controllers/spot-automation/spot-group/config.js

Add icon to spot group supported resource type item

Add icon to spot group supported resource type item

---

package.json

Change build script

---

src/controllers/add-ons/excel/index.js
src/lib/excel.js
src/lib/utils.js
src/routes/add-ons/excel.js

excel data parser 추가
- 코드 리팩토링
- excel export 시, file_link에 담아 보냄
- data type에 따른 data converting
- datetime: timezone에 맞춰 readable하게 변환 (ex. 2021-03-23 02:00:02)
- list: \n로 join (ex. ['a', 'b', 'c'] -> 'a\nb\nc')
- 그 외 데이터는 엑셀에 그대로 들어감
뭐 더 할 게 있을 거 같은데...뭔가 찜찜한 이 기분은 뭘까요🙃

Add data converting to excel library

---

src/controllers/spot-automation/spot-group/index.js
src/routes/spot-automation/spot-group.js

Add spot automation spot group get candidates api

Add spot automation spot group get candidates api

---

src/controllers/spot-automation/spot-group/config.js

Add EKS to supported resource types of spot group

Add EKS to supported resource types of spot group

---

package.json

Trigger github action

---

package.json

dev 스크립트 변경
dev script 가 build 된 dist 폴더를 바라봐서 변경사항이 실시간 반영 안되는 문제 해결

Update dev script to skip the build process

---

src/controllers/spot-automation/spot-group/list-spot-group-members.ts
src/routes/spot-automation/spot-group.ts

Spot Group 내 프로젝트에 연결된 멤버를 가져오는 API 추가

Add a listSpotGroupMembers API

---

src/controllers/spot-automation/spot-group/get-spot-group-instance-count.ts
src/controllers/spot-automation/spot-group/get-spot-group-servers.ts
src/controllers/spot-automation/spot-group/index.ts
src/routes/spot-automation/spot-group.ts

스팟 그룹 내 인스턴스 개수(total / ondemand / spot)를 가져오는 API 개발
스팟 그룹 내 서버 아이디를 가져오는 API의 구조 개선

Add a getSpotGroupInstanceCount API

---

src/controllers/spot-automation/spot-group/get-cloud-service-instance-count.ts
src/controllers/spot-automation/spot-group/get-spot-group-instance-count.ts
src/controllers/spot-automation/spot-group/get-spot-group-instance-cpu.ts
src/controllers/spot-automation/spot-group/get-spot-group-instance-disk.ts
src/controllers/spot-automation/spot-group/get-spot-group-instance-state.ts
src/controllers/spot-automation/spot-group/get-spot-group-instance-types.ts
src/controllers/spot-automation/spot-group/get-spot-group-loadbalancer-count.ts
src/controllers/spot-automation/spot-group/get-spot-group-servers.ts
src/controllers/spot-automation/spot-group/utils.ts
src/routes/spot-automation/spot-group.ts

Spot Group에서 데이터 표기를 위한 API 추가

Add Spot Group APIs

---

src/controllers/spot-automation/spot-group/get-cloud-service-instance-count.ts
src/controllers/spot-automation/spot-group/utils.ts

Fix a EKS Node Group compatibility

---

src/controllers/spot-automation/spot-group/get-spot-group-resources.ts
src/routes/spot-automation/spot-group.ts

사용 중인 Spot Group 내 클라우드 서비스 목록을 가져오는 API

Add a get-spot-group-resources API

---

src/controllers/spot-automation/spot-group/get-spot-group-metrics.ts
src/routes/spot-automation/spot-group.ts

Spot Group에 연결된 메트릭 정보를 가져오는 API 개발

Add a get-spot-group-metrics API

---

src/controllers/spot-automation/spot-group/get-spot-group-instance-count.ts
src/controllers/spot-automation/spot-group/get-spot-group-instance-state.ts
src/controllers/spot-automation/spot-group/get-spot-group-instance-types.ts
src/controllers/spot-automation/spot-group/get-spot-group-loadbalancer-count.ts
src/controllers/spot-automation/spot-group/get-spot-group-schema.ts
src/controllers/spot-automation/spot-group/utils.ts
src/routes/spot-automation/spot-group.ts

Spot Group에 연결된 Instance 또는 Load Balancer의 Schema를 가져오는 API 개발
Spot Group Utils의 성능 개선 작업

Add a get-spot-group-schema API

---

src/controllers/spot-automation/spot-group/get-spot-group-cloud-service-type.ts
src/controllers/spot-automation/spot-group/index.ts
src/routes/spot-automation/spot-group.ts

Spot Group API 추가
Spot Group에서 cloud service type을 보여주기 위한 API 추가

Add get spot group cloud service type API

---

src/controllers/spot-automation/spot-group/get-spot-group-interrupt-history.ts
src/controllers/spot-automation/spot-group/get-spot-group-interrupt.ts
src/routes/spot-automation/spot-group.ts

Spot Group의 인터럽트 정보를 가져오는 API 추가

Add get-spot-group-interrupt APIs

---

src/controllers/spot-automation/history/index.ts
src/controllers/spot-automation/interrupt/index.ts
src/controllers/spot-automation/spot-group/get-spot-group-instance-count-history.ts
src/controllers/spot-automation/spot-group/get-spot-group-instance-count-v1.ts
src/controllers/spot-automation/spot-group/get-spot-group-instance-count.ts
src/controllers/spot-automation/spot-group/get-spot-group-interrupt-history.ts
src/controllers/spot-automation/spot-group/get-spot-group-interrupt-summary.ts
src/controllers/spot-automation/spot-group/get-spot-group-interrupt.ts
src/controllers/spot-automation/spot-group/get-spot-group-metrics.ts
src/routes/spot-automation/spot-group.ts

Spot Group Interrupt 조회 API 추가
Spot Group 내 Instance 개수 조회 API 개선
Spot Group 내 Instance 개수 히스토리 API 추가

Add spot group stat APIs

---

src/controllers/add-ons/page-schema/identityServiceAccount/default-schema/details.json.tmpl
src/controllers/add-ons/page-schema/identityServiceAccount/default-schema/table.json.tmpl
src/controllers/add-ons/page-schema/inventoryCloudService/default-schema/details.json
src/controllers/add-ons/page-schema/inventoryCloudService/default-schema/table.json.tmpl
src/controllers/add-ons/page-schema/inventoryServer/default-schema/details.json
src/controllers/add-ons/page-schema/inventoryServer/default-schema/table.json
src/controllers/power-scheduler/schedule/schedule-resource-groups.ts
src/controllers/statistics/topic/cloud-service-resources.ts
src/controllers/statistics/topic/daily-update-cloud-service.ts
src/controllers/statistics/topic/daily-update-server.ts
src/factories/config/user-config.ts
src/factories/inventory/resource-group.ts
src/factories/power-scheduler/schedule-rule.ts
src/factories/power-scheduler/schedule.ts
src/lib/utils.ts

tags의 타입을 Array of Object에서 Object로 변경
기본 datetime format을 ISO8601로 변경

Change tags and datetime field type

---

src/controllers/statistics/topic/cloud-service-resources.ts
src/controllers/statistics/topic/daily-update-cloud-service.ts
src/controllers/statistics/topic/daily-update-server.ts
src/lib/utils.ts

통계 결과에 대한 tags는 아직 Array of object 형태이기 때문에 이에 대한 버그 수정함

Fix a tags response bug

---

src/routes/spot-automation/spot-group.ts

get-spot-group-saving-cost API의 Router에 누락되어 추가

Add router

---

src/controllers/spot-automation/spot-group/get-spot-group-saving-cost-history.ts

Spot Group의 Saving Cost Hisotry의 Mock 데이터 버그 수정

Fix a response mock data

---

src/controllers/spot-automation/spot-group/get-spot-group-saving-cost-history.ts
src/routes/spot-automation/spot-group.ts

Spot Group의 Saving Cost를 구하는 API에 Instance Count 추가

Add instance_count data to get-spot-group-saving-cost-history

---

src/controllers/power-scheduler/schedule/index.ts

Add Azure VirtualMachine, VmScaleSet in drop down
- [O] 신규 기능
Add Azure VirtualMachine, VmScaleSet at options

Add Azure VirtualMachine, VmScaleSet in drop down

---

src/controllers/statistics/topic/power-scheduler-schedules.ts

Project 별 Power Schedule 목록 표시시 desired state 버그 수정

Fix a power scheduler status bug

---

src/controllers/spot-automation/spot-group/get-spot-group-saving-cost-history.ts
src/controllers/spot-automation/spot-group/get-spot-group-saving-cost.ts
src/controllers/statistics/topic/power-scheduler-saving-cost.ts
src/controllers/statistics/topic/spot-automation-saving-cost.ts

Fix mock data

---

src/lib/excel.ts

excel에서 시간 데이터 안 나오는 버그 수정
- timestamp 대신 iso8601 대응으로 변경

Fix time formatter in excel.ts

---

deploy/helm/config/production.json

Change sample production.json for deployment

---

src/lib/excel.ts

Fix excel bug

---

src/controllers/add-ons/page-schema/identityServiceAccount/index.ts
src/controllers/add-ons/page-schema/index.ts
src/controllers/add-ons/page-schema/inventoryCloudService/index.ts
src/controllers/add-ons/page-schema/inventoryServer/index.ts
src/routes/add-ons/page-schema.ts

Add customizing page schema 

---

src/controllers/add-ons/page-schema/index.ts
src/controllers/add-ons/page-schema/inventoryCloudService/default-schema/details.json
src/controllers/add-ons/page-schema/inventoryCloudService/default-schema/search.json.tmpl
src/controllers/add-ons/page-schema/inventoryCloudService/default-schema/table.json.tmpl
src/controllers/add-ons/page-schema/inventoryCloudService/index.ts
src/controllers/add-ons/page-schema/inventoryServer/default-schema/details.json
src/controllers/add-ons/page-schema/inventoryServer/default-schema/table.json
src/controllers/add-ons/page-schema/inventoryServer/index.ts

Cloud Service 및 Server의 Default Schema 변경
커스텀 필드 기능 업데이트와 함께 is_optional 필드 스펙 추가

Change cloud service and server's default schema

---

src/lib/authentication.ts
src/lib/excel.ts

File name prefix 속성 추가 
Excel을 만들 때 파일 이름 앞에 prefix 추가 (cloud service, service account 등..)

Add file name prefix property

---

src/controllers/add-ons/page-schema/inventoryCloudService/default-schema/table.json.tmpl
src/controllers/add-ons/page-schema/inventoryServer/default-schema/table.json

Change server and cloud service's default schema

---

src/controllers/add-ons/page-schema/inventoryCloudService/default-schema/details.json
src/controllers/add-ons/page-schema/inventoryServer/default-schema/details.json

Cloud Service 및 Server의 Default Schema 수정

Fix server and cloud service default schema

---

src/lib/excel.ts

excel에 headerMessage 추가
- 엑셀 디자인 수정
- header message가 있을 경우 엑셀 상단에 추가

Add headerMessage to excel

---

src/lib/grpc-client/well-known-type.ts

gRPC 요청 시 boolean type이 누락되는 버그가 발생하여 수정함

Fix a grpc's boolean type request bug.

---

src/lib/excel.ts

Update minor things in excel

---

src/controllers/identity/project/tree-project.ts

tree-project에서 project item에 `has_permission: true` 추가

Add has_permission to project

---

src/controllers/identity/project/tree-project.ts

Fix check child bug in project tree api

Fix check child bug in project tree api

---

src/lib/excel.ts

Fix empty cell data bug 
[CLOUD-4357](https://pyengine.atlassian.net/browse/CLOUD-4357)

Fix empty cell data bug 

---

src/controllers/identity/project-group/index.ts
src/controllers/identity/project/index.ts
src/controllers/inventory/cloud-service-type/index.ts
src/controllers/spot-automation/spot-group/index.ts

Favorite bug 수정
https://pyengine.atlassian.net/browse/CLOUD-4375
리소스를 삭제할 시에 userConfig 내의 favorite도 함께 삭제

Fix delete favorite resource bug

---

src/lib/excel.ts

Change vertical alignment of excel to top

---

src/lib/excel.ts

Fix excel file name

---

deploy/helm/config/nginx.conf
deploy/helm/config/proxy.conf

Excel Download 시 504 Gateway timeout 에러가 발생하여 Nginx의 Connection Timeout을 1분에서 10분으로 변경

Change nginx configuration

---

deploy/helm/Chart.yaml
deploy/helm/config/proxy.conf

Change nginx log configuration

---

deploy/helm/config/proxy.conf

Change a nginx log path

---

deploy/helm/Chart.yaml

Update helm chart version

---

src/controllers/inventory/job/index.ts
src/routes/inventory/job.ts

JobTask의 Progress를 가져오는  API 개발

Add a get-job-progress API

---

src/controllers/inventory/job/index.ts

get-job-progress API에 job_status 필드 추가

Add job_status to get-job-progress API

---

src/controllers/identity/service-account/index.ts
src/controllers/identity/user/index.ts
src/controllers/inventory/cloud-service/index.ts
src/controllers/inventory/collector/index.ts
src/controllers/secret/secret-group/index.ts

API Key 개수 API 작업
1. Stat API를 활용하여 각 user가 가지고 있는 API Count 가져오기
2. ErrorModel 타입을 잘못된 path에서 부르고있는 페이지들 수정

Add get user API Key count API

---

src/controllers/add-ons/page-schema/inventoryServer/default-schema/search.json
src/controllers/add-ons/page-schema/inventoryServer/default-schema/table.json

Server의 기본 스미카 변경
- 디스크 / 네트워크 Throughput은 Size 타입으로 변경
- CPU는 CPU Utilization으로 이름 변경

Change server's default page schema

---

src/controllers/statistics/topic/project-page.ts

Improve the performance of statistical query

---

config/default.json
src/controllers/notification/project-channel/index.ts
src/controllers/notification/protocol/index.ts
src/controllers/notification/user-channel/index.ts
src/routes/index.ts
src/routes/notification/index.ts
src/routes/notification/project-channel.ts
src/routes/notification/protocol.ts
src/routes/notification/user-channel.ts

Notification API 작업
Notification Protocol, User channel, Project channel 관련 API 작업

Add notification API

---

src/controllers/monitoring/escalation-policy/index.ts
src/routes/monitoring/escalation-policy.ts
src/routes/monitoring/index.ts

Add monitoring escalation-policy API

---

src/controllers/notification/project-channel/index.ts
src/controllers/notification/user-channel/index.ts
src/routes/notification/project-channel.ts
src/routes/notification/user-channel.ts

Add set schedule API

---

config/default.json
package-lock.json
package.json
src/lib/grpc-client/index.ts

Support TLS communication in gRPC client.

---

src/controllers/add-ons/autocomplete/config.json

Region 검색 자동 완성에  Provider 정보 추가

Add provider to region autocomplete

---

src/controllers/monitoring/alert/index.ts
src/controllers/statistics/topic/alert-state-count.ts
src/routes/statistics/topic.ts

feat: add alert-state-count API

---

src/controllers/monitoring/event-rule/index.ts
src/controllers/monitoring/webhook/index.ts
src/routes/monitoring/event-rule.ts
src/routes/monitoring/index.ts

Add event rule API

---

src/controllers/identity/project/index.ts

Fix project controller

---

src/controllers/monitoring/alert/index.ts
src/controllers/monitoring/maintenance-window/index.ts

changeAlertState, closeMaintenanceWindows API 코드리뷰 반영

Fix alert, maintenance window APIs

---

src/controllers/monitoring/event/index.ts
src/routes/monitoring/event.ts
src/routes/monitoring/index.ts

Add event API

---

src/controllers/monitoring/alert/index.ts
src/controllers/monitoring/alert/type.ts
src/routes/monitoring/alert.ts

Add createNote and updateAssignee when alerts' state is changed

feat: add createNote and updateAssignee

---

src/controllers/monitoring/dashboard/alert-by-project.ts
src/controllers/monitoring/dashboard/current-project-status.ts
src/controllers/monitoring/dashboard/top5-project-activity-alert-details.ts

alert dashboard api들 수정
- top5-project-activity-alert-details.ts: period가 아니라 start, end를 받는 것으로 변경
- alert-by-project: activated_projects param 추가

fix: alert dashboard apis

---

src/controllers/monitoring/dashboard/daily-alert-history.ts

fix: daily-alert-history bug

---

config/default.json
src/controllers/notification/notification/index.ts
src/routes/notification/index.ts
src/routes/notification/notification.ts

notification > notification api 추가

feat: add notification/notification apis

---

src/lib/grpc-client/index.ts

gRPC Client의 매개변수 버그 수정
현재는 버전이 필요하지 않아서 입력 매개변수로 버전을 수정했더니 기존 코드와의 호환 문제가 발생하여 롤백함

fix: default argument bug

---

config/default.json
src/lib/authentication.ts
src/lib/grpc-client/index.ts

관리자 콘솔을 위한 에스컬레이션 기능 개발
특정 도메인(ex: root)에 대해 에스컬레이션 기능을 설정하면 다른 도메인에 접근 가능

feat: escalation features for admin console

---

src/controllers/identity/project-group/index.ts
src/controllers/identity/project/index.ts

프로젝트에 사용자 추가 시 is_external_user 파라메터 추가

feat: add is_external_user parameter to add_members API

---

config/default.json
package-lock.json
package.json
src/controllers/identity/user/index.ts
src/routes/identity/user.ts

feat: add get IP API

---

src/lib/authentication.ts

identity.Token.refresh API는 위임 기능이 의도치않게 동작하는 코드 버그 수정

fix: fix a escalation bug

---

config/default.json
src/controllers/cost-analysis/budget/index.ts
src/controllers/cost-analysis/cost-query-set/index.ts
src/controllers/cost-analysis/cost/index.ts
src/controllers/cost-analysis/dashboard/index.ts
src/controllers/cost-analysis/data-source-rule/index.ts
src/controllers/cost-analysis/data-source/index.ts
src/controllers/cost-analysis/exchange-rate/index.ts
src/controllers/cost-analysis/schedule/index.ts
src/routes/cost-analysis/budget.ts
src/routes/cost-analysis/cost-query-set.ts
src/routes/cost-analysis/cost.ts
src/routes/cost-analysis/dashboard.ts
src/routes/cost-analysis/data-source-rule.ts
src/routes/cost-analysis/data-source.ts
src/routes/cost-analysis/exchange-rate.ts
src/routes/cost-analysis/index.ts
src/routes/cost-analysis/schedule.ts
src/routes/index.ts

Add cost analysis APIs

---

src/controllers/cost-analysis/cost/analyze-costs.ts
src/controllers/cost-analysis/cost/index.ts
src/lib/grpc-client/proto/query.proto
src/routes/cost-analysis/cost.ts

feat: implement cost analyze api

---

src/controllers/cost-analysis/cost/analyze-costs.ts
src/lib/grpc-client/proto/query.proto

비용 분석 결과를 테이블 형태로 받아 볼 때 마지막 일 기준으로 정렬

feat: add sort by last day

---

src/controllers/cost-analysis/cost/analyze-costs.ts
src/lib/grpc-client/proto/query.proto

ACCUMULATED 방식으로 비용 계산 시 usd cost 기준으로 정렬 적용

Change cost analysis query

---

config/default.json
src/controllers/add-ons/page-schema/inventoryCloudService/default-schema/details.json
src/controllers/add-ons/page-schema/inventoryCloudService/default-schema/search.json.tmpl
src/controllers/add-ons/page-schema/inventoryCloudService/default-schema/table.json.tmpl
src/controllers/add-ons/page-schema/inventoryServer/default-schema/details.json
src/controllers/add-ons/page-schema/inventoryServer/default-schema/search.json
src/controllers/add-ons/page-schema/inventoryServer/default-schema/table.json

/identity/domain/get API 호출 시 token을 누락하여 전송하는 문제가 있어 버그 수정

fix authentication issue

---

src/controllers/add-ons/page-discovery/config.json

fix: page discovery config

---

src/controllers/add-ons/page-discovery/config.json

fix: page-discovery config

---

src/controllers/add-ons/menu/config.json

feat: add lnb menu

---

deploy/helm/config/proxy.conf

feat: update nginx config

---

src/controllers/add-ons/page-schema/inventoryServer/index.ts

create/update를 나누던 부분을 모두 set으로 변경하였습니다.

fix: page schema update issue

---

src/controllers/inventory/cloud-service/get-data.ts
src/controllers/inventory/server/get-data.ts
src/lib/utils.ts

feat: use getValueByPath in getData apis
